name: Release

permissions: read-all

on:
  workflow_run:
    workflows: [ "MR build and tests" ]
    types: [completed]
    branches: [ "master" ]

concurrency:
  group: release-${{ github.event.workflow_run.head_sha || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'master'
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: release-publish
          path: ./release-publish
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Replace values on appsettings.json
        shell: bash
        env:
          TOKEN: ${{ secrets.BETTERSTACK_SOURCE_TOKEN }}
          ENDPOINT: ${{ secrets.BETTERSTACK_ENDPOINT }}
        run: |
          FILE="${{ github.workspace }}/release-publish/appsettings.json"
          if [ ! -f "$FILE" ]; then
            echo "File not found: $FILE"
            exit 1
          fi
      
          sed -i -E "s|\"sourceToken\"\s*:\s*\"[^\"]*\"|\"sourceToken\": \"${TOKEN}\"|" "$FILE"
          sed -i -E "s|\"betterStackEndpoint\"\s*:\s*\"[^\"]*\"|\"betterStackEndpoint\": \"${ENDPOINT}\"|" "$FILE"
          
      - name: Deploy
        uses: ChristopheLav/iis-deploy@v1
        with:
          website-name: 'felipesoares-001-site2'
          msdeploy-service-url: ${{ secrets.FTP_SERVER }}
          msdeploy-username: ${{ secrets.FTP_USERNAME }}
          msdeploy-password: ${{ secrets.FTP_PASSWORD }}
          source-path: ${{ github.workspace }}\release-publish\
          skip-extra-files: 0
